In [1]:
!pip install pytest

Defaulting to user installation because normal site-packages is not writeable


# NUMPY
    * stands for NUMERICAL PYTHON
    * used when mathematical operations need to be performed on arryas/matrices etc

In [4]:
import numpy as np

In [5]:
print(np.__version__)

1.21.5


## NUMPY ARRAY

In [7]:
list1=[1,2,3,4,5,6,7,8,9]
np.array(list1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# N-Dimensional array
type(np.array(list1))

numpy.ndarray

In [12]:
arr=np.array(list1)

In [13]:
arr.dtype

dtype('int32')

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr.shape

(9,)

In [19]:
print(arr.ndim)

1


In [21]:
print(arr.itemsize)     

4


In [23]:
#returns size in bytes used by entire array
print(arr.nbytes)

36


## ARRAY OPERATIONS
    * Simple array math operations

### Why numpy arrays are better than lists ?

In [29]:
list1 = [10,20,30,40,50,60,70,80,90]
list2 = [2,4,3,6,5,6,5,8,9]

list3=[]
for i in range (len(list1)):
    list3.append(list1[i]/list2[i])
    
print(list3)

[5.0, 5.0, 10.0, 6.666666666666667, 10.0, 10.0, 14.0, 10.0, 10.0]


In [30]:
arr1 = np.array([10,20,30,40,50,60,70,80,90])
arr2 = np.array([2,4,3,6,5,6,5,8,9])

# element by element division
arr1/arr2

array([ 5.        ,  5.        , 10.        ,  6.66666667, 10.        ,
       10.        , 14.        , 10.        , 10.        ])

In [31]:
arr1 = np.array([10,20,30,40,50,60,70,80,90])
arr2 = np.array([2])

arr1/arr2

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [32]:
arr1 = np.array([10,20,30,40,50,60,70,80,90])
arr2 = np.array([2,4,3,6,5,6,5,8])

arr1/arr2

ValueError: operands could not be broadcast together with shapes (9,) (8,) 

In [34]:
# generate numpy array using arange(start, stop, stepsize)

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
list1 = [10,20,30,40,50,60,70,80,90]
arr1 = np.array([10,20,30,40,50,60,70,80,90])

print(list1.__sizeof__())
arr1.nbytes

136


36

## TYPES OF NUMPY ARRAY


In [38]:
# dtype = mention datatype with size
# int8, int16, int32, int64

# -128 to 127
arr1 = np.array([10,20,30,40,50,34,54,12,5464],dtype='int8')
print(arr1)

[10 20 30 40 50 34 54 12 88]


In [39]:
arr2 = np.array([10.,12.,23.,24.,65.,54.], dtype = 'float16')
print(arr2)

[10. 12. 23. 24. 65. 54.]


### Create a list with range (1, 1,00,000)

In [53]:
list1 = []
n=0
for i in range (1,100000):
    n=n+1
    list1.append(n)
ls=sum(list1)
print(ls)

4999950000


In [62]:
import time

size=100000

def list_version():
    begin=time.time()
    list1 = list(range(size))
    list2 = list(range(size))
    list3=[]
    for i in range (1,100000):
        list3.append(list1[i]+list2[i])
    #print(list3)
    end=time.time()
    print(end - begin)

def numpy_version():
    begin=time.time()
    arr1=np.arange(0,100000)
    arr2=np.arange(0,100000)
    arr1+arr2
    end=time.time()
    print(end - begin)
    
list_version()
numpy_version()

0.027169466018676758
0.0006945133209228516


## 2-D ARRAY

In [68]:
# 2D array -> MATRIX

arr4=np.array([[0,1,2,3,4,5,6,7,],
              [10,11,12,13,14,15,16,17]])

In [70]:
# shape =(row,columns)

arr4.shape

(2, 8)

In [67]:
# shape[0]= rows, shape[1]=columns

arr4.shape[0], arr4.shape[1]

(2, 8)

In [71]:
# returns dimension

print(arr4.ndim)

2


#### INDEXING

In [72]:
# slicing in numpy array
# displays first row 

arr4[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
# display single element row

print(arr4[1][3])
print(arr4[1,3])

13
13


In [79]:
# indexing 2D array
# first -1 is for row, -1 is for column

arr4[-1,-1]

17

In [81]:
# update in numpy array

arr4[-1,-1]=15
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15, 16, 15]])

#### SLICING

In [82]:
# slicing to 2D array
# displays all rows and columns except last row and last column

arr4[:-1,:-1]

array([[0, 1, 2, 3, 4, 5, 6]])

## 3D ARRAY

In [118]:
# 3D array -> MULTI DIMENSIONAL ARRAY / TENSOR

arr=np.array([[[0,1,2,3,4,5,6,7,],
               [10,11,12,13,14,15,16,17]],
              
              [[0,1,2,3,4,5,6,7,],
               [10,11,12,13,14,15,16,17]],
              
              [[0,1,2,3,4,5,6,7,],
               [10,11,12,13,14,15,16,17]]])

In [124]:
print(arr[:-1,:-1,:-1])

[[[0 1 2 3 4 5 6]]

 [[0 1 2 3 4 5 6]]]


In [120]:
print(arr)

[[[ 0  1  2  3  4  5  6  7]
  [10 11 12 13 14 15 16 17]]

 [[ 0  1  2  3  4  5  6  7]
  [10 11 12 13 14 15 16 17]]

 [[ 0  1  2  3  4  5  6  7]
  [10 11 12 13 14 15 16 17]]]


In [121]:
# RANK, ROWS, COLUMNS

arr.shape

(3, 2, 8)

In [87]:
# shows the length of all elements(3*2*8)
# size = number of elements in an array

arr.size

48

In [88]:
print(arr[1][1][4])
print(arr[1,1,4])

14
14


#### Empty array and fill it with some constant values

In [91]:
arr = np.empty(6, dtype='int8')
arr

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [92]:
arr1 = np.arange(0,36).reshape(6,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [96]:
arr1 = np.arange(0,36).reshape(4,3,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

 #### REVERSE AN ARRAY

In [98]:
arr3 = np.arange(50)
arr3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [83]:
import numpy as np

In [84]:
arr= np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [86]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [90]:
arr2=np.arange(0,36).reshape(6,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [93]:
# ud() -> up/down
np.flipud(arr2)

array([[30, 31, 32, 33, 34, 35],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [96]:
# lr() -> left/right
print(arr2)
np.fliplr(arr2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24],
       [35, 34, 33, 32, 31, 30]])

In [99]:
# up/down and left/right
print(arr2)
np.flip(arr2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

#### Create an array using methods
    * np.ones()
    * np.zeros()

In [100]:
# shape 3 rows, 6 columns

np.zeros((6,6), dtype="float16")

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float16)

    * Identity Matrix 
        * Generate a N x N identity matrix. The default matrix dtype is float64
        * Diagonal values are 1, non-diagonal values are 0

In [101]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [102]:
np.identity(7,dtype = 'int8')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [103]:
# (start,stop,no of elements)
# equally spaced 

np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
## exercise :
[ 1 1 1 1 1 1 1 1 
  1 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 1
  1 1 1 1 1 1 1 1]

In [1]:
import numpy as np

In [9]:
row = int(input("Enter rows : "))
col = int(input("Enter columns : "))

#arr = np.identity(row)
arr = np.zeros((row,col), dtype="int8")

for i in range (row):
    for j in range (col):
        if (i==0 or j==0):
            arr[i][j]=1
        elif (i==(row-1) or j==(col-1)):
            arr[i][j]=1
        else:
            arr[i][j]=0

print(arr)

Enter rows : 5
Enter columns : 6
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [8]:
row = int(input("Enter rows : "))
col = int(input("Enter columns : "))

arr = np.ones((row,col),dtype="int8")

for i in range (row):
    for j in range (col):
        if(i%2 == 0):
            if(j%2 == 0):
                arr[i][j]=1
            else:
                arr[i][j]=0
        else:
            if(j%2 != 0):
                arr[i][j]=1
            else:
                arr[i][j]=0 

print(arr)

Enter rows : 5
Enter columns : 5
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [12]:
arr = np.ones((5,5))
# slicing in an array
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
arr = np.ones((5,5))
# slicing in an array
arr[1::2,0::2] = 0
arr[0::2,1::2] = 0
arr

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

### NULL VALUES

In [15]:
arr = np.ones((5,5))
arr[1::2,0::2] = np.nan
arr[0::2,1::2] = np.nan
arr

array([[ 1., nan,  1., nan,  1.],
       [nan,  1., nan,  1., nan],
       [ 1., nan,  1., nan,  1.],
       [nan,  1., nan,  1., nan],
       [ 1., nan,  1., nan,  1.]])

In [19]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = np.nan
arr

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1., nan, nan, nan,  1.],
       [ 1., nan, nan, nan,  1.],
       [ 1., nan, nan, nan,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
# isnan() - returns boolean value, True for missing data, false for not-missing data
np.isnan(arr) == True

array([[False, False, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False]])

In [24]:
# np.count_nonzero() counts False/0 values
np.count_nonzero(~np.isnan(arr))

16

In [26]:
np.count_nonzero(np.isnan(arr))

9

In [27]:
np.count_nonzero(arr)

25

In [ ]:
[A,B,C,D
 E,F,G,H
 I,J,K,L
 M,N,O,P
 Q,R,S,T
 U,V,W,X]

A,E,I,O,U - np.nan

In [111]:
import random
import string 

arr=np.empty((6,4),dtype="object")

for i in range(6):
    for j in range(4):
        arr[i][j] = random.choice(string.ascii_uppercase)
        

count=0;
for i in range(6):
    for j in range(4):
        if(arr[i][j] == 'A' or arr[i][j] == 'E' or arr[i][j] == 'I' or arr[i][j] == 'O' or arr[i][j] == 'U'):
            arr[i][j] = str(np.nan)
            count+=1


print(count)
arr

2


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [119]:
arr2=[chr(i) for i in range(65,89)]

for i in range(len(arr2)):
    if arr2[i]=='A' or arr2[i]=='E' or arr2[i]=='I' or arr2[i]=='O' or arr2[i]=='U':
        arr2[i]='nan'
print(arr2)

['nan', 'B', 'C', 'D', 'nan', 'F', 'G', 'H', 'nan', 'J', 'K', 'L', 'M', 'N', 'nan', 'P', 'Q', 'R', 'S', 'T', 'nan', 'V', 'W', 'X']


In [120]:
c=0
for i in range(len(arr2)):
    if arr2[i]=='nan':
        c += 1
arr3=np.array(arr2)
print(np.reshape(arr3,(4,6)))
print("\nCount is :",c)

[['nan' 'B' 'C' 'D' 'nan' 'F']
 ['G' 'H' 'nan' 'J' 'K' 'L']
 ['M' 'N' 'nan' 'P' 'Q' 'R']
 ['S' 'T' 'nan' 'V' 'W' 'X']]

Count is : 5


# NUMPY 
    *Array calculation method

In [100]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
# sum of all elements 
arr.sum()

21

In [103]:
# axis = 0(sum of all columns)
# apply sum() along 0th axis

arr.sum(axis = 0)

array([5, 7, 9])

In [104]:
# axis = 1(sum of all rows)
# apply sum() along 1st axis

arr.sum(axis = 1)

array([ 6, 15])

In [105]:
arr.min()

1

In [106]:
# returns index of maximum value along axis

arr = [0.,0.,0.,1.,0.,0.,0.]
np.argmax(arr)

3

In [107]:
arr = np.arange(0,36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [108]:
np.argmax(arr, axis=0)

array([5, 5, 5, 5, 5, 5], dtype=int64)

In [109]:
np.argmax(arr, axis=1)

array([5, 5, 5, 5, 5, 5], dtype=int64)

# Statistical Analysis of ARRAY
    * CENTRAL TENDANCY : 
        * MEAN: average of sequence (sum of elements / no of elements)
        * MEDIAN: middle term of a sorted array
            * no of terms even : (n/2 + (n/2+1))/2
            * no of terms odd : (n+1)/2
        * MODE: most frequent value

In [124]:
arr = np.array([1,2,4,7,8,11,13])

np.median(arr)

7.0

In [125]:
arr = np.array([1,2,4,8,11,13])

np.median(arr)

6.0

In [126]:
# standard deviation of array
np.std(arr)

4.5

In [127]:
# variance of an array
np.var(arr)

20.25